apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-v2  # Nombre único para evitar colisiones en la UI
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pulidovpe/kubernetes-in-hardening-lab
    targetRevision: HEAD
    path: apps/webapp
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
