apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp-sa
  namespace: produccion
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webapp-role
  namespace: produccion
rules:
- apiGroups: ['']
  resources: ['configmaps']
  verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webapp-role-binding
  namespace: produccion
subjects:
- kind: ServiceAccount
  name: webapp-sa
  namespace: produccion
roleRef:
  kind: Role
  name: webapp-role
  apiGroup: rbac.authorization.k8s.io
